### ISSUE TITLE
Does not appear to be working on Windows 11

### ISSUE THREAD

**Issue by splatboydev** [pulse-browser/gluon#17]
### I have installed the required dependencies and followed all the instructions, but it does not work.

![image](https://user-images.githubusercontent.com/64037464/191929549-e6d6eff5-a0f6-4c30-b811-d92237f77801.png)
![image](https://user-images.githubusercontent.com/64037464/191929651-892abf10-605c-4dba-ac7b-ae001ea60d82.png)
![image](https://user-images.githubusercontent.com/64037464/191929701-6f047240-69f8-4abc-9ba2-a1a9f8f96773.png)
![image](https://user-images.githubusercontent.com/64037464/191929780-8d930341-579f-43ed-bf49-6c2306c51573.png) (latest mozillabuild version)
![image](https://user-images.githubusercontent.com/64037464/191929936-12f0daed-f20c-4c51-81bb-49d79185d5b7.png)
### yarn version: ![image](https://user-images.githubusercontent.com/64037464/191930149-3237e729-0684-40d6-bfff-1840c0c1f6dc.png)
![image](https://user-images.githubusercontent.com/64037464/191930274-51bd5d60-9432-454c-8c0f-fa43c9496f15.png)
### choco version: ![image](https://user-images.githubusercontent.com/64037464/191930322-a8c7d9e8-739b-4f78-ab10-23576501055a.png)

**All steps** go fine until `gluon download`, where this error happens:
![image](https://user-images.githubusercontent.com/64037464/191930593-e43043c9-f111-473e-ba72-57fab6c7b399.png)

I have tried resetting the folder and re-configuring the gluon project but it doesn't seem to affect anything.

**Comment by PressJump** [comment]
The directory you have the browser in which is "Frenon Browser," it appears that it contains a space. Tar does not like spaces between directory names and will detect it as a parameter in the cli. This applies to other parts of the browser as well. I believe removing the space will fix your problem with tar not being able to find your directory due to the space.

Example Below (Using Space):
![image](https://user-images.githubusercontent.com/40802367/192007179-8b9cd2ca-8e66-4bb6-a14c-58e17c177e4d.png)

Closing the issue for now.

**Comment by splatboydev** [comment]
Originally, I was using ``C:\Users\<>\OneDrive\Documents\GitHub\freon``, so this is true but the same problem happened either way. I moved it to a different folder but I'll try to re-run it now in case it works.

**Comment by splatboydev** [comment]
It looks like it's working now, so this was an error on my part. Sorry about that and thanks for the help

**Comment by PressJump** [comment]
No problem at all. Windows builds for the tool are very experimental so if you have any problems feel free to always create an issue. The reason I believed it was a directory issue was due to your terminal output which can be seen below.
![image](https://user-images.githubusercontent.com/40802367/192044807-2f0e39cc-1f72-4e5b-aede-145d20c9ddad.png)

**Comment by splatboydev** [comment]
Is it therefore possible to use something like ``tar <args> "C:\etc etc\etc (dir with spaces)" <other args>`` in the tool?

**Comment by PressJump** [comment]
Yes, in theory. Attempting it with the git bash version of tar on Windows (what gluon uses for Windows) by enclosing the directory in double quotes yields the same error. There is undoubtedly a solution, but this is not the only part of the tool that requires no-spaces in the directory. If my memory serves me correctly, this also becomes an issue with browser symlinks so one way or the other, it will fail. For large code-bases, it is best practice not to use a directory with spaces due to this kind of problem.
