### ISSUE TITLE
Ensure that `.gluon/` is in `.gitignore`

### ISSUE THREAD

**Issue by trickypr** [pulse-browser/gluon#24]

**Comment by splatboydev** [comment]
This would explain it not appearing in the gitignore.

gitignoreContents is what is written to the ``.gitignore`` file after setup.
![image](https://user-images.githubusercontent.com/64037464/198832174-c87ce5fb-ccc2-463c-8475-44ae15f463f1.png)
Logically, it should be `'\n.dotbuild/\n.gluon/\nengine/\nfirefox-*/\nnode_modules/\n'` instead of `'\n.dotbuild/\n.gluon\nengine/\nfirefox-*/\nnode_modules/\n'`.

I don't think the change is worth a PR.

**Comment by splatboydev** [comment]
But maybe it is, so I'll open one anyway.
